---
app:
  serviceType: ClusterIP
  image: skraft/code-with-quarkus:1.0.0-SNAPSHOT
  s2iJava:
    builderImage: fabric8/s2i-java
  openjdk11:
    builderImage: registry.access.redhat.com/ubi8/openjdk-11
  envs:
    JAVA_APP_JAR: /deployments/quarkus-run.jar
